<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\JmServer.Contracts\JmServer.Contracts.csproj" />
    <ProjectReference Include="..\JmServer.GameIntegration\JmServer.GameIntegration.csproj" />
    <ProjectReference Include="..\JmServer.Protocol\JmServer.Protocol.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="SuperSocket.Client" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" />
  </ItemGroup>
</Project>
